const patients=[
{id:1,name:'Giulia Bianchi',type:'Individuale',site:'Parma',rate:65,balance:0,consent:'Firmato',start:'12/05/2026',email:'giulia.demo@example.com',phone:'333 000 1122'},
{id:2,name:'Marco e Anna',type:'Coppia',site:'Online',rate:90,balance:180,consent:'Firmato',start:'03/02/2026',email:'coppia.demo@example.com',phone:'333 000 2244'},
{id:3,name:'Luca Verdi',type:'Individuale',site:'Modena',rate:65,balance:65,consent:'Mancante',start:'01/09/2026',email:'luca.demo@example.com',phone:'333 000 3366'},
{id:4,name:'Sara Neri',type:'Genitoriale',site:'Bologna',rate:80,balance:0,consent:'2° firma mancante',start:'28/08/2026',email:'sara.demo@example.com',phone:'333 000 4488'}];
const nav=[['dashboard','⌂','Home'],['agenda','▦','Agenda'],['patients','♧','Pazienti'],['payments','▣','Pagamenti'],['docs','□','Documenti'],['messages','☵','Messaggi'],['stats','▥','Statistiche'],['resources','◇','Risorse'],['settings','⚙','Impostazioni']];let current='dashboard';
function renderNav(){document.querySelector('#nav').innerHTML=nav.map(n=>`<button class='navbtn ${current===n[0]?'active':''}' onclick="go('${n[0]}')">${n[1]} &nbsp;${n[2]}</button>`).join('')}
function go(v){current=v;renderNav();const names={dashboard:'Dashboard',agenda:'Agenda',patients:'Pazienti',payments:'Pagamenti',docs:'Documenti',messages:'Messaggi',stats:'Statistiche',resources:'Risorse',settings:'Impostazioni'};title.textContent=names[v];subtitle.textContent=v==='dashboard'?'Sabato 19 settembre 2026':'Studio Rocchi · Beta 2';views[v]();window.scrollTo(0,0)}
const appts=[['09:00','Giulia Bianchi','Parma','Confermato'],['10:30','Marco e Anna','Online','Da confermare'],['14:30','Luca Verdi','Modena','Confermato'],['16:00','Sara Neri','Bologna','Confermato'],['17:30','Nuovo colloquio','Online','Da confermare']];
function apptRows(){return appts.map(a=>`<div class='appt'><div class='time'>${a[0]}</div><div><b>${a[1]}</b><div class='muted'>${a[2]}</div></div><span class='pill ${a[3]==='Da confermare'?'warn':''}'>${a[3]}</span></div>`).join('')}
const views={dashboard(){view.innerHTML=`
<div class='masthead'>
  <div class='mast-copy'>
    <div class='studio-title'>STUDIO ROCCHI</div>
    <div class='studio-sub'>PSICOLOGIA · SESSUOLOGIA · CRIMINOLOGIA</div>
    <div class='studio-motto'>ASCOLTARE · COMPRENDERE · TRASFORMARE</div>
  </div>
  <div class='botanical'>⌁ 𖤣 𖥧 𖡼</div>
  <div class='mast-words'>Persone<br>relazioni<br>possibilità</div>
</div>
<div class='welcome'><div><h1>Buongiorno, Stefania</h1><div class='date'>Sabato 19 settembre 2026</div></div><div class='quote'>“La cura è anche organizzazione.”</div></div>
<div class='grid4'>
 <div class='stat'><span class='stat-icon'>▣</span><strong>5</strong><small>Appuntamenti oggi</small></div>
 <div class='stat'><span class='stat-icon'>♧</span><strong>28</strong><small>Pazienti attivi</small></div>
 <div class='stat'><span class='stat-icon'>▤</span><strong>3</strong><small>Documenti da firmare</small></div>
 <div class='stat'><span class='stat-icon'>€</span><strong>4</strong><small>Pagamenti in sospeso</small></div>
</div>
<div class='dashboard-grid'>
 <div class='card agenda-card'><div class='card-head'><h2>Agenda di oggi</h2><button class='linkbtn' onclick="go('agenda')">Vedi agenda →</button></div>${apptRows()}
   <div class='agenda-actions'><button class='primary' onclick='openAppointment()'>＋ Nuovo appuntamento</button><button class='ghost' onclick='openMonthly()'>Programma il mese</button></div>
 </div>
 <div class='card mini-calendar'><div class='card-head'><h2>Settembre 2026</h2><span>‹ &nbsp;&nbsp; ›</span></div>
   <div class='weekdays'><b>L</b><b>M</b><b>M</b><b>G</b><b>V</b><b>S</b><b>D</b></div>
   <div class='monthdays'>${Array.from({length:35},(_,i)=>{let d=i-1;return d>0&&d<=30?`<span class="${d===19?'today':''}">${d}</span>`:`<span></span>`}).join('')}</div>
   <div class='legend'><span>● Appuntamenti</span><span>● Impegni personali</span><span>● Formazione</span><span>● Altro</span></div>
 </div>
 <div class='card reminders'><div class='card-head'><h2>Promemoria</h2><button class='linkbtn'>Vedi tutti →</button></div>
   ${['Inviare relazione a Lazzari','Richiedere rateizzazione a Barbara','Preparare slide UTE (lezione 2)','Follow-up mail ex corsisti','Comprare frigo studio'].map(x=>`<label class='reminder'><input type='checkbox'> <span>${x}</span><b>⋮</b></label>`).join('')}
   <button class='primary wide'>＋ Nuovo promemoria</button>
 </div>
 <div class='card recent'><div class='card-head'><h2>Pazienti recenti</h2><button class='linkbtn' onclick="go('patients')">Vedi tutti →</button></div>
   <div class='patient-bubbles'>${patients.map(p=>`<div onclick='patient(${p.id})'><span>${p.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><b>${p.name}</b><small>Prossima: 22/09</small></div>`).join('')}</div>
 </div>
 <div class='card latest'><div class='card-head'><h2>Ultimi documenti</h2><button class='linkbtn' onclick="go('docs')">Vedi tutti →</button></div>
   ${['Relazione psicologica.docx','Consenso informato.pdf','PAI - Report.pdf','Preventivo percorso coppia.pdf'].map((x,i)=>`<div class='docrow'><span>▤</span><div><b>${x}</b><small>${i?'Modificato ieri':'Modificato oggi, 10:24'}</small></div><b>⋮</b></div>`).join('')}
 </div>
 <div class='quote-card'><img src='logo-transparent.png'><blockquote>«Le persone<br>non sono problemi<br>da risolvere,<br>ma storie da comprendere.»</blockquote></div>
</div>`},
agenda(){let days=Array.from({length:30},(_,i)=>`<div class='day'><b>${i+1} SET</b>${[2,5,9,12,16,19,23,26,29].includes(i+1)?`<div class='event'>16:00 · Paziente demo<br>Parma</div>`:''}</div>`).join('');view.innerHTML=`<div class='toolbar'><button class='primary' onclick='openAppointment()'>＋ Appuntamento</button><button class='ghost' onclick='openMonthly()'>Programma mese</button><button class='ghost' onclick="showToast('Vista disponibilità attivata')">Mostra slot liberi</button><select><option>Tutte le sedi</option><option>Parma</option><option>Modena</option><option>Bologna</option><option>Online</option></select></div><div class='calendar'>${days}</div>`},
patients(){view.innerHTML=`<div class='card'><div class='toolbar'><input placeholder='Cerca paziente…'><button class='primary' onclick='openPatient()'>＋ Nuovo paziente</button></div><table class='table'><thead><tr><th>Paziente</th><th>Percorso</th><th>Sede</th><th>Tariffa</th><th>Saldo</th><th>Consenso</th></tr></thead><tbody>${patients.map(p=>`<tr class='click' onclick='patient(${p.id})'><td><b>${p.name}</b></td><td>${p.type}</td><td>${p.site}</td><td>€${p.rate}</td><td>${p.balance?`<span class='pill danger'>€${p.balance}</span>`:'✓'}</td><td><span class='pill ${p.consent==='Firmato'?'':'warn'}'>${p.consent}</span></td></tr>`).join('')}</tbody></table></div>`},
payments(){view.innerHTML=`<div class='grid4'><div class='stat'><small>Incassi settembre</small><strong>€4.285</strong></div><div class='stat'><small>Da saldare</small><strong>€245</strong></div><div class='stat'><small>Parma</small><strong>€2.340</strong></div><div class='stat'><small>Altre sedi + online</small><strong>€1.945</strong></div></div><div class='card' style='margin-top:16px'><h2>Movimenti recenti</h2><table class='table'><tr><th>Data</th><th>Paziente</th><th>Sede</th><th>Importo</th><th>Stato</th></tr><tr><td>18/09</td><td>Giulia Bianchi</td><td>Parma</td><td>€65</td><td><span class='pill'>Pagato · POS</span></td></tr><tr><td>17/09</td><td>Marco e Anna</td><td>Online</td><td>€90</td><td><span class='pill danger'>Da pagare</span></td></tr></table></div>`},
docs(){view.innerHTML=`<div class='card'><h2>Documenti e modelli</h2><div class='alert'>📄 Consenso informato adulto <button class='ghost' onclick="showToast('Modello aperto')">Apri modello</button></div><div class='alert'>📄 Consenso minore — doppia firma <button class='ghost' onclick="showToast('Modello aperto')">Apri modello</button></div><div class='alert'>📄 Consenso percorso di coppia <button class='ghost' onclick="showToast('Modello aperto')">Apri modello</button></div><div class='alert'>📝 Modello relazione psicologica <button class='ghost' onclick="showToast('Generazione Word/PDF prevista nella Beta 2')">Genera</button></div></div>`},
messages(){view.innerHTML=`<div class='card'><h2>Messaggi automatici</h2><p class='muted'>I modelli sono già previsti; l'invio reale verrà collegato dopo.</p>${['Conferma appuntamento','Promemoria seduta','Date mensili','Richiesta pagamento','Invio consenso informato'].map(x=>`<div class='alert'><b>${x}</b><div class='muted'>Email / WhatsApp · modello modificabile</div></div>`).join('')}</div>`},
stats(){view.innerHTML=`<div class='grid4'><div class='stat'><small>Sedute settembre</small><strong>68</strong></div><div class='stat'><small>Incassi</small><strong>€4.285</strong></div><div class='stat'><small>Disdette</small><strong>6</strong></div><div class='stat'><small>Nuovi pazienti</small><strong>3</strong></div></div><div class='two'><div class='card'><h2>Attività per sede</h2><p>Parma ███████████ 54%</p><p>Online █████ 22%</p><p>Modena ███ 14%</p><p>Bologna ██ 10%</p></div><div class='card'><h2>Disponibilità</h2><p><b>4 slot</b> liberi nei prossimi 7 giorni.</p><button class='ghost' onclick="go('agenda')">Vedi in agenda</button></div></div>`},
resources(){view.innerHTML=`<div class='card'><h2>Risorse</h2><p class='muted'>Spazio per modelli, test, materiali clinici e risorse dello studio.</p><div class='resource-grid'><div class='detail'><small>Modelli</small><b>Consensi e relazioni</b></div><div class='detail'><small>Test</small><b>Archivio strumenti</b></div><div class='detail'><small>Materiali</small><b>Handout per pazienti</b></div></div></div>`},
settings(){view.innerHTML=`<div class='card'><h2>Impostazioni studio</h2><div class='detailgrid'><div class='detail'><small>Sedi</small><b>Parma · Modena · Bologna · Online</b></div><div class='detail'><small>Google Calendar</small><b>Non collegato</b></div><div class='detail'><small>Email</small><b>Non collegata</b></div></div><p class='muted' style='margin-top:16px'>La Beta usa solo dati dimostrativi. Le integrazioni reali e la gestione dei dati sanitari richiederanno autenticazione, ruoli, cifratura, backup e registro accessi.</p></div>`}};
function patient(id){const p=patients.find(x=>x.id===id);title.textContent='Scheda paziente';view.innerHTML=`<div class='card'><div class='patient-head'><div class='patient-title'><div class='avatar'>${p.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div><h2>${p.name}</h2><div class='muted'>${p.type} · ${p.site} · dal ${p.start}</div></div></div><button class='ghost' onclick="showToast('Modifica scheda: demo')">Modifica</button></div><div class='tabs'><div class='tab active'>Panoramica</div><div class='tab'>Appuntamenti</div><div class='tab'>Note</div><div class='tab'>Pagamenti</div><div class='tab'>Documenti</div><div class='tab'>Consensi</div></div><div class='detailgrid'><div class='detail'><small>Prossimo appuntamento</small><b>22/09 · 16:00</b></div><div class='detail'><small>Tariffa</small><b>€${p.rate}</b></div><div class='detail'><small>Saldo aperto</small><b>${p.balance?'€'+p.balance:'Nessuno'}</b></div><div class='detail'><small>Consenso</small><b>${p.consent}</b></div><div class='detail'><small>Email</small><b>${p.email}</b></div><div class='detail'><small>Telefono</small><b>${p.phone}</b></div></div><div class='two'><div class='card'><h2>Ultimi incontri</h2><div class='appt'><div>15/09</div><div><b>Seduta effettuata</b><div class='muted'>Nota breve presente</div></div><span class='pill'>Pagata</span></div><div class='appt'><div>08/09</div><div><b>Seduta effettuata</b></div><span class='pill'>Pagata</span></div></div><div class='card'><h2>Azioni</h2><div class='toolbar'><button class='ghost' onclick='openAppointment()'>Nuovo appuntamento</button><button class='ghost' onclick="showToast('Link consenso preparato')">Invia consenso</button><button class='ghost' onclick="showToast('Richiesta pagamento preparata')">Richiedi pagamento</button></div></div></div></div>`}
function openAppointment(){modal.classList.remove('hidden');modalBody.innerHTML=`<h2>Nuovo appuntamento</h2><div class='form'><label>Paziente<select>${patients.map(p=>`<option>${p.name}</option>`).join('')}</select></label><label>Sede<select><option>Parma</option><option>Modena</option><option>Bologna</option><option>Online</option></select></label><label>Data<input type='date' value='2026-09-22'></label><label>Ora<input type='time' value='16:00'></label><label>Tariffa<input type='number' value='65'></label><label>Ricorrenza<select><option>Nessuna</option><option>Settimanale</option><option>Ogni 2 settimane</option><option>Mensile</option></select></label><label class='full'>Nota organizzativa<textarea placeholder='Nessuna nota clinica qui…'></textarea></label><div class='full'><button class='primary' onclick="saveDemo('Appuntamento salvato nella demo')">Salva appuntamento</button></div></div>`}
function openMonthly(){modal.classList.remove('hidden');modalBody.innerHTML=`<h2>Programma il mese</h2><p class='muted'>Genera in una volta tutte le date del mese per un paziente.</p><div class='form'><label>Paziente<select>${patients.map(p=>`<option>${p.name}</option>`).join('')}</select></label><label>Mese<select><option>Ottobre 2026</option><option>Novembre 2026</option></select></label><label>Giorno<select><option>Martedì</option><option>Mercoledì</option><option>Giovedì</option><option>Venerdì</option></select></label><label>Ora<input type='time' value='16:00'></label><label>Sede<select><option>Parma</option><option>Modena</option><option>Bologna</option><option>Online</option></select></label><label>Invio<select><option>Prepara link di conferma</option><option>Non inviare</option></select></label><div class='full'><button class='primary' onclick="saveDemo('4 appuntamenti creati · link di conferma preparato')">Crea appuntamenti</button></div></div>`}
function openPatient(){modal.classList.remove('hidden');modalBody.innerHTML=`<h2>Nuovo paziente</h2><div class='form'><label>Nome e cognome<input></label><label>Telefono<input></label><label>Email<input type='email'></label><label>Percorso<select><option>Individuale</option><option>Coppia</option><option>Genitoriale</option><option>Altro</option></select></label><label>Sede<select><option>Parma</option><option>Modena</option><option>Bologna</option><option>Online</option></select></label><label>Tariffa<input type='number' value='65'></label><label class='full'>Contatto di emergenza<input></label><div class='full'><button class='primary' onclick="saveDemo('Paziente aggiunto alla demo')">Crea scheda</button></div></div>`}
function closeModal(){modal.classList.add('hidden')}function saveDemo(s){closeModal();showToast(s)}function showToast(s){toast.textContent=s;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2300)}renderNav();views.dashboard();
